### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by onokatio** [onokatio/NanoWalletBrowserApp#1]
- [x] UI
  - [x] Using window function
- [x] Functions
  - [x] Fix cookie bugs
- [x] Other
  - [x] Upload to web store.
